/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define LM35_PIN 0
#define GREENLED_PIN 1
#define YELLOWLED_PIN 2
#define REDLED_PIN 3
#define BUTTON_PIN 10

#define FAN_PIN 7

int main(void)
{
	//Enable Clocks
	RCC->‎AHB1ENR‎ |= (0b01 << 0); // GPIOA
	RCC->‎AHB1ENR‎ |= (0b01 << 1); // GPIOB
	RCC->APB2ENR |= (0b01 << 8); // ADC1

	ADC1->CR2 |= (0b01 << 0);	// ADON
	ADC1->CR1 |= (0b00 << 24);  // 12 bit

	for(int i = 0; i < 1000; ++i);

	ADC1->SQR3 = 0;

	//OUTPUTs
	GPIOA->MODER |= (1 << (2 * GREENLED_PIN));
	GPIOA->MODER |= (1 << (2 * YELLOWLED_PIN));
	GPIOA->MODER |= (1 << (2 * REDLED_PIN));
	GPIOB->MODER |= (1 << (2 * FAN_PIN));

	//INPUTs
	GPIOA->MODER &= ~(3 << (2 * BUTTON_PIN));

	GPIOA->MODER = 0;

	while(1){
		ADC1->CR2 |= (1 << 30);
		while(!(ADC1->SR & (1 << 1)));
		int ADC_read = ADC1->DR;
		float volt = (ADC_read * (3.3 )/ 4095);
		float temp = volt * 100;
	}

}
